# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 03:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendships',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='friendships',
            name='user',
        ),
        migrations.DeleteModel(
            name='Friendships',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
