# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('friends_app', '0002_auto_20161121_0305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('update_dt', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('update_dt', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='friendships',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='friendsfriend', to='friends_app.User'),
        ),
        migrations.AddField(
            model_name='friendships',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usersfriend', to='friends_app.User'),
        ),
    ]
